imports:
    - { resource: image_variations.yml }
    - { resource: views.yml }

parameters:
    # `layout` locationId
    layout_id: 54

    # `folder` in the media library containing all the releases
    release_container_location_id: 57
    # `folder` in the media library containing all the betas
    beta_container_location_id: 58

    # `blog` locationId
    blog.location_id: 71
    # `blog_post` limit on the `blog` page
    blog.posts_limit: 10
    # `authors` folder locationId
    blog.authors_container_location_id: 72
    # `bundles_list` locationId
    bundles.location_id: 168
    # 'bundles_list` elements limit on `bundles_list` page
    bundles.cards_limit: 10
    # 'bundles' cache expiration time in seconds
    bundles.cache_expiration_time: 604800
    # names of excluded bundle maintainers
    bundles.excluded_maintainers: ['ezrobot']
    # overwrites default tag view page template
    netgen_tags.default.tag_view.pagelayout: 'pagelayout.html.twig'
    # overwrites default tag related content limit
    eztags.default.tag_view.related_content_list.limit: 10
    # community metrics location ID
    community_metrics.location_id: 218
    # community metrics decoded iframe URL
    community_metrics.iframe_url: 'https://communitymetrics.ez.no/app/kibana#/dashboard/e8dca940-7d3a-11e7-a3ec-639c36c57655?embed=true&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1y,mode:quick,to:now))'
    # product feedback location ID
    product_feedback.location_id: 362
    # product feedback iframe URL
    product_feedback.iframe_url: 'https://portal.productboard.com/vsjzmdg4emeihrpkxcfz6nrz'

    # default png compression level used in image_variations.yml
    images.default_png_compression_level: 9
    # default jpeg quality used in image_variations.xml
    images.default_jpeg_quality: 90

# configuration for the CommentsBundle
ez_comments:
    system:
        default:
            default_provider: disqus
            content_comments:
                my_comment_ruleset:
                    enabled: true
                    match:
                        Identifier\ContentType:
                            - blog_post
            disqus:
                shortname: ezplatform-com

# additional Twig configuration
twig:
    globals:
        blogLocationId: '%blog.location_id%'
        bundlesListLocationId: '%bundles.location_id%'
        communityMetricsIframeUrl: '%community_metrics.iframe_url%'
        productFeedbackIframeUrl: '%product_feedback.iframe_url%'
