imports:
    - { resource: image_variations.yml }
    - { resource: views.yml }

parameters:
    # `layout` locationId
    layout_id: 54

    # `folder` in the media library containing all the releases
    release_container_location_id: 57
    # `folder` in the media library containing all the betas
    beta_container_location_id: 58

    # `blog` locationId
    blog.location_id: 71
    # `blog_post` limit on the `blog` page
    blog.posts_limit: 10
    # `authors` folder locationId
    blog.authors_container_location_id: 72

# configuration for the CommentsBundle
ez_comments:
    system:
        default:
            default_provider: disqus
            content_comments:
                my_comment_ruleset:
                    enabled: true
                    match:
                        Identifier\ContentType:
                            - blog_post
            disqus:
                shortname: ezplatform-com

# additional Twig configuration
twig:
    globals:
        blogLocationId: '%blog.location_id%'

# additional Assetic configuration
assetic:
    assets:
        js_default:
            inputs:
                ~
        css_default:
            inputs:
                - 'assets/css/ezplatform-com.css'
                - 'assets/css/embed.css'
                - 'assets/css/responsive.css'
                - 'assets/css/slider.css'
                - 'assets/css/download.css'
                - 'assets/css/error.css'
                - 'assets/css/blog.css'
                - 'assets/css/blog_post.css'
        js_prism:
            inputs:
                - 'assets/js/prism.js'
        css_prism:
            inputs:
                - 'assets/css/prism.css'
