ezpublish:
    system:
        default:
            image_variations:
                # dedicated to images embedded in the blog_post body
                blog_post_full_width:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [800] }

                blog_author:
                    reference: ~
                    filters:
                        - { name: geometry/scaleexact, params: [60, 60] }
                blog_post_author:
                    reference: ~
                    filters:
                        - { name: geometry/scaleexact, params: [80, 80] }
                blog_thumbnail:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [710] }
