ezpublish:
    system:
        default:
            pagelayout: pagelayout.html.twig
            user:
                layout: pagelayout.html.twig

            content_view:
                full:
                    home:
                        controller: ez_query:LocationQueryAction
                        params:
                            omitted_location_ids:
                                - '%blog.location_id%'
                                - '%blog.authors_container_location_id%'
                            query:
                                query_type: AppBundle:Children
                                parameters:
                                    parent_location_id: 2
                                    excluded_content_types: layout
                                assign_results_to: items
                        template: full\home.html.twig
                        match:
                            Id\Location: 2
                    blog:
                        controller: ez_query:LocationQueryAction
                        params:
                            query:
                                query_type: AppBundle:Children
                                parameters:
                                    parent_location_id: '%blog.location_id%'
                                    limit: '%blog.posts_limit%'
                                    sorting_content_type: blog_post
                                    sorting_field: publication_date
                                    sorting_order: desc
                                assign_results_to: posts
                        template: full\blog.html.twig
                        match:
                            Identifier\ContentType: blog
                    blog_post:
                        template: full\blog_post.html.twig
                        match:
                            Identifier\ContentType: blog_post

                line:
                    blog_post:
                        template: line\blog_post.html.twig
                        match:
                            Identifier\ContentType: blog_post

                row:
                    banner_slider:
                        template: row\banner_slider.html.twig
                        match:
                            Identifier\ContentType: banner_slider
                    download_section:
                        template: row\download_section.html.twig
                        controller: ezplatform.controller.download:showAction
                        match:
                            Identifier\ContentType: download_section

                blog:
                    author:
                        template: parts\blog\author.html.twig
                        match:
                            Identifier\ContentType: author

                blog_post:
                    author:
                        template: parts\blog_post\author.html.twig
                        match:
                            Identifier\ContentType: author

                embed:
                    code:
                        template: embed\code.html.twig
                        match:
                            Identifier\ContentType: code
                    youtube:
                        template: embed\youtube.html.twig
                        match:
                          Identifier\ContentType: youtube
                    image:
                        template: embed\image.html.twig
                        match:
                            Identifier\ContentType: image
