ezpublish:
    system:
        site_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"
            user:
                layout: "@ezdesign/pagelayout.html.twig"

            content_view:
                full:
                    home:
                        controller: ez_query:LocationQueryAction
                        params:
                            omitted_location_ids:
                                - '%blog.location_id%'
                                - '%blog.authors_container_location_id%'
                                - '%bundles.location_id%'
                            query:
                                query_type: AppBundle:Children
                                parameters:
                                    parent_location_id: 2
                                    excluded_content_types:
                                        - layout
                                        - article
                                        - bundle_list
                                assign_results_to: items
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Id\Location: 2
                    blog:
                        controller: ez_query:LocationQueryAction
                        params:
                            query:
                                query_type: AppBundle:Children
                                parameters:
                                    parent_location_id: '%blog.location_id%'
                                    limit: '%blog.posts_limit%'
                                    sorting_content_type: blog_post
                                    sorting_field: publication_date
                                    sorting_order: desc
                                assign_results_to: posts
                        template: "@ezdesign/full/blog.html.twig"
                        match:
                            Identifier\ContentType: blog
                    blog_post:
                        template: "@ezdesign/full/blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post
                    community_metrics:
                        template: "@ezdesign/full/community_metrics.html.twig"
                        match:
                            Id\Location: '%community_metrics.location_id%'
                    product_feedback:
                        template: "@ezdesign/full/product_feedback.html.twig"
                        match:
                            Id\Location: '%product_feedback.location_id%'
                    article:
                        template: "@ezdesign/full/article.html.twig"
                        match:
                            Identifier\ContentType: article
                    bundle_list:
                        controller: app.controller.bundle:showBundlesListAction
                        template: "@ezdesign/full/bundle_list.html.twig"
                        match:
                            Identifier\ContentType: bundle_list

                line:
                    blog_post:
                        template: "@ezdesign/line/blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post
                    bundle:
                        template: "@ezdesign/line/bundle_card.html.twig"
                        match:
                            Identifier\ContentType: bundle

                row:
                    banner_slider:
                        template: "@ezdesign/row/banner_slider.html.twig"
                        match:
                            Identifier\ContentType: banner_slider
                    download_section:
                        template: "@ezdesign/row/download_section.html.twig"
                        controller: app.controller.download:showAction
                        match:
                            Identifier\ContentType: download_section

                blog:
                    author:
                        template: "@ezdesign/parts/blog/author.html.twig"
                        match:
                            Identifier\ContentType: author

                blog_post:
                    author:
                        template: "@ezdesign/parts/blog_post/author.html.twig"
                        match:
                            Identifier\ContentType: author

                embed:
                    code:
                        template: "@ezdesign/embed/code.html.twig"
                        match:
                            Identifier\ContentType: code
                    youtube:
                        template: "@ezdesign/embed/youtube.html.twig"
                        match:
                          Identifier\ContentType: youtube
                    image:
                        template: "@ezdesign/embed/image.html.twig"
                        match:
                            Identifier\ContentType: image
