services:
    app.controller.download:
        class: AppBundle\Controller\DownloadController
        arguments:
            - '@ezpublish.api.service.search'
            - '@app.query_type.latest_releases'
            - '%release_container_location_id%'
            - '%beta_container_location_id%'
    app.controller.blog:
        class: AppBundle\Controller\BlogController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@app.query_type.children'
            - '%blog.location_id%'
            - '%blog.posts_limit%'
    app.controller.package:
        class: AppBundle\Controller\PackageController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@ezpublish.urlalias_router'
            - '@app.query_type.packages'
            - '@app.packagist_service_provider'
            - '@form.factory'
            - '@router.default'
            - '@eztags.api.service.tags'
            - '@ezpublish.api.service.location'
            - '%packages.location_id%'
            - '%packages.cards_limit%'
            - '%packages.categories_parent_tag_id%'
    app.controller.tag:
        class: AppBundle\Controller\TagController
        arguments:
            - '@templating'
            - '@eztags.api.service.tags'
            - '%eztags.default.tag_view.related_content_list.limit%'
