services:
    app.controller.download:
        class: AppBundle\Controller\DownloadController
        arguments:
            - '@ezpublish.api.service.search'
            - '@app.query_type.latest_releases'
            - '%release_container_location_id%'
            - '%beta_container_location_id%'

    app.controller.blog:
        class: AppBundle\Controller\BlogController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@app.query_type.children'
            - '%blog.location_id%'
            - '%blog.posts_limit%'
    app.controller.bundle:
        class: AppBundle\Controller\BundleController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@app.query_type.bundles'
            - '@app.packagist_service_provider'
            - '%bundles.location_id%'
            - '%bundles.cards_limit%'
    app.controller.tag:
        class: AppBundle\Controller\TagController
        arguments:
            - '@templating'
            - '@eztags.api.service.tags'
            - '%eztags.default.tag_view.related_content_list.limit%'
