services:
    app.twig_extension.field_options:
        class: AppBundle\Twig\FieldOptionsTwigExtension
        arguments:
            - '@ezpublish.api.service.content_type'
        tags:
            - name: twig.extension
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
